### ISSUE TITLE
Multiple People Pickers on one Page

### ISSUE THREAD

**Issue by krusk** [jasonvenema/sharepoint-angular-peoplepicker#2]
Hi Jason,
I need to use multiple people pickers in one page. The first field works, but those after it don't. Ex:

```
<sp-people-picker name="CC7" id="CC7" ng-model="$scope.cc7" min-entries="1" max-entries="1" allow-duplicates="false" show-login="false" show-title="true" min-characters="2" app-web-url="$scope.spAppWebUrl" />

<sp-people-picker name="CC8" id="CC8" ng-model="$scope.cc8" min-entries="1" max-entries="1" allow-duplicates="false" show-login="false" show-title="true" min-characters="2" app-web-url="$scope.spAppWebUrl" />
```

Am I missing  a method to allow multiple people pickers in a single form?

Thanks,

K.

**Comment by brannmar** [comment]
I am having the same problem I have narrowed it down to that all the fields has to be unique, what I mean is that i.e. the hidden field is not unique and can therefore not hold a value for each peoplepicker. Have a look at this: https://github.com/OfficeDev/PnP/tree/master/Components/Core.PeoplePicker#appendix-a-adding-multiple-people-pickers-on-a-form-by-karim-kameka

I also would like to have multiple peoplpickers! Thanks!

**Comment by jasonvenema** [comment]
The directive was definitely only designed to support one per page, as there will be conflicting element IDs otherwise. We may be able to work around this limitation by keeping track of assigned IDs, and referencing the appropriate element when it's being updated with lookup results.

**Comment by aloizeau** [comment]
I'm started a new control from this code and I have find a solution to add multicontrol in the same page.
The solution is : use attrs.id to create html elements and in the instance name of the peoplePicker.
I send the solution here when I finished it.

**Comment by krusk** [comment]
Great news. Thank you.
